-- ═══════════════════════════════════════════════════════════════════════════
-- FLYWAY MIGRATION V3: CREATE POLICIES TABLE
-- ═══════════════════════════════════════════════════════════════════════════
--
-- RELATIONSHIP: customers (1) ─── (N) policies
-- One customer can have multiple insurance policies (life, health, vehicle, etc.)
--
-- DESIGN DECISIONS:
-- ─────────────────
-- policy_number: Auto-generated unique identifier in format POL-YYYYMMDD-XXXXX
--   • Business-facing ID (shown to customers, used in documents)
--   • Unlike the internal DB `id`, this is human-readable
--   • Generated programmatically in PolicyService, not via DB sequence
--   • INTERVIEW TIP: Separate "surrogate key" (id) from "natural key" (policy_number)
--
-- NUMERIC type for monetary values:
--   • NUMERIC(15, 2) = up to 15 digits total, 2 decimal places
--   • NEVER use FLOAT/DOUBLE for money — floating point imprecision causes
--     rounding errors (e.g., 0.1 + 0.2 ≠ 0.3 in floating point)
--   • Java maps NUMERIC to BigDecimal which preserves exact precision
--   • INTERVIEW TIP: Always use NUMERIC/DECIMAL for financial calculations.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS policies (
    -- SURROGATE KEY (internal database identifier)
    id              BIGSERIAL       PRIMARY KEY,

    -- BUSINESS KEY (customer-facing policy number)
    -- Generated by PolicyService as: "POL-" + date + "-" + random5digits
    -- UNIQUE + NOT NULL: each policy has a globally unique policy number
    policy_number   VARCHAR(30)     NOT NULL UNIQUE,

    -- POLICY DETAILS
    policy_name     VARCHAR(200)    NOT NULL,

    -- Policy type maps to PolicyType enum: LIFE, HEALTH, VEHICLE, PROPERTY, TRAVEL
    policy_type     VARCHAR(30)     NOT NULL,

    -- Policy description/terms summary
    description     TEXT,

    -- FINANCIAL FIELDS — using NUMERIC to avoid floating-point precision issues
    -- coverage_amount: maximum payout the insurer will pay for a claim
    coverage_amount NUMERIC(15, 2)  NOT NULL CHECK (coverage_amount > 0),

    -- premium_amount: monthly/annual amount the customer pays for the policy
    -- Calculated by PremiumCalculationService based on coverage + risk level
    premium_amount  NUMERIC(15, 2)  NOT NULL CHECK (premium_amount > 0),

    -- POLICY PERIOD
    start_date      DATE            NOT NULL,
    end_date        DATE            NOT NULL,
    -- Business rule enforced at DB level: end_date must be after start_date
    CONSTRAINT chk_policy_dates CHECK (end_date > start_date),

    -- STATUS: maps to PolicyStatus enum: PENDING, ACTIVE, EXPIRED, CANCELLED
    status          VARCHAR(20)     NOT NULL DEFAULT 'PENDING',

    -- PREMIUM PAYMENT FREQUENCY: MONTHLY, QUARTERLY, SEMI_ANNUAL, ANNUAL
    premium_frequency VARCHAR(20)   NOT NULL DEFAULT 'MONTHLY',

    -- FOREIGN KEY: Many policies belong to one customer
    -- ON DELETE CASCADE: when customer is deleted, their policies are also deleted
    customer_id     BIGINT          NOT NULL,
    CONSTRAINT fk_policy_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,

    -- AUDIT FIELDS
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- ─── INDEXES ────────────────────────────────────────────────────────────────
-- policy_number: Most common search field (customer looks up their policy by number)
CREATE UNIQUE INDEX IF NOT EXISTS idx_policies_policy_number ON policies(policy_number);

-- customer_id: Used in "list all policies for a customer" query
CREATE INDEX IF NOT EXISTS idx_policies_customer_id ON policies(customer_id);

-- status: Used in dashboard queries (count ACTIVE, EXPIRED policies)
CREATE INDEX IF NOT EXISTS idx_policies_status ON policies(status);

-- policy_type: Used for filtering/searching by type
CREATE INDEX IF NOT EXISTS idx_policies_type ON policies(policy_type);

-- Composite: finding active policies for a customer (common query pattern)
CREATE INDEX IF NOT EXISTS idx_policies_customer_status ON policies(customer_id, status);

-- ─── COMMENTS ───────────────────────────────────────────────────────────────
COMMENT ON TABLE policies IS 'Insurance policies. One customer can have many policies (One-to-Many).';
COMMENT ON COLUMN policies.policy_number IS 'Business-facing unique ID (e.g. POL-20240115-12345). Generated by PolicyService.';
COMMENT ON COLUMN policies.coverage_amount IS 'Maximum amount insurer will pay per claim. NUMERIC to avoid floating-point errors.';
COMMENT ON COLUMN policies.premium_amount IS 'Amount customer pays per period. Calculated via risk-based premium formula.';
