package com.insurance.entity;

import com.insurance.enums.ClaimStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║                           CLAIM ENTITY                                  ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║                                                                          ║
 * ║  Represents an insurance claim submitted by a customer against a        ║
 * ║  specific policy. Claims go through a review workflow from PENDING       ║
 * ║  to either APPROVED or REJECTED.                                        ║
 * ║                                                                          ║
 * ║  RELATIONSHIPS:                                                          ║
 * ║  Policy   (1) ─── (N) Claim   [@ManyToOne, FK: policy_id]              ║
 * ║  Customer (1) ─── (N) Claim   [@ManyToOne, FK: customer_id]            ║
 * ║                                                                          ║
 * ║  DESIGN: Denormalized customer_id                                       ║
 * ║  ─────────────────────────────────────────────────────────────────────  ║
 * ║  Although customer_id could be derived via claim → policy → customer,   ║
 * ║  storing it directly enables:                                            ║
 * ║  1. Fast "list all claims by customer" query (no JOIN through policies) ║
 * ║  2. Direct ownership enforcement at DB level                            ║
 * ║  3. Better index utilization for customer-centric queries               ║
 * ║                                                                          ║
 * ║  BUSINESS RULES (enforced in ClaimService):                             ║
 * ║  • Policy must be ACTIVE to submit a claim                              ║
 * ║  • Claim amount ≤ Policy coverage amount                                ║
 * ║  • Customer can only claim on their own policies                        ║
 * ║  • Only ADMIN/AGENT can approve or reject claims                        ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */
@Entity
@Table(
    name = "claims",
    indexes = {
        @Index(name = "idx_claims_policy_id", columnList = "policy_id"),
        @Index(name = "idx_claims_customer_id", columnList = "customer_id"),
        @Index(name = "idx_claims_status", columnList = "status"),
        @Index(name = "idx_claims_claim_number", columnList = "claim_number", unique = true)
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Claim {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Business-facing claim reference number.
     * Format: CLM-YYYYMMDD-NNNNN (e.g., CLM-20240510-00001)
     * Generated by ClaimService on submission.
     */
    @Column(name = "claim_number", nullable = false, unique = true, length = 30)
    private String claimNumber;

    /**
     * Customer's description of the insured event that led to this claim.
     * Stored as TEXT (no length limit) to allow detailed descriptions.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    /**
     * The amount the customer is claiming from the insurance company.
     * Business rule: claimAmount ≤ policy.coverageAmount (enforced in ClaimService)
     * NUMERIC(15,2) → BigDecimal, same as policy financial fields.
     */
    @Column(name = "claim_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal claimAmount;

    /**
     * Current status of the claim in the review workflow.
     * Transitions: PENDING → UNDER_REVIEW → APPROVED / REJECTED
     * Initial state on submission: PENDING
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private ClaimStatus status = ClaimStatus.PENDING;

    /**
     * Notes added by the reviewing agent/admin explaining the decision.
     * Required when status = REJECTED (must explain why).
     * Optional (but recommended) when status = APPROVED.
     */
    @Column(name = "review_notes", columnDefinition = "TEXT")
    private String reviewNotes;

    /**
     * When was this claim submitted? Set automatically on creation.
     */
    @Column(name = "submitted_at", nullable = false)
    @Builder.Default
    private LocalDateTime submittedAt = LocalDateTime.now();

    /**
     * When did an agent/admin review this claim?
     * NULL until claim moves out of PENDING state.
     */
    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;

    /**
     * Date when the insured event (incident) occurred.
     * Must be within the policy period (startDate to endDate).
     */
    @Column(name = "incident_date", nullable = false)
    private LocalDate incidentDate;

    /**
     * @ManyToOne: Many claims can be submitted against one policy.
     * @JoinColumn: This table has the FK column "policy_id".
     *   → Claim is the OWNING side of the Policy-Claim relationship.
     * fetch = LAZY: Policy not auto-loaded (avoids eager loading of financial data).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "policy_id", nullable = false)
    private Policy policy;

    /**
     * @ManyToOne: Many claims can belong to one customer.
     * Denormalized FK for direct customer-based queries.
     * fetch = LAZY: Customer not auto-loaded.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // ─── HELPER METHODS ───────────────────────────────────────────────────

    /**
     * Checks if the claim is in a terminal state (cannot transition further).
     * Used in ClaimService to prevent re-reviewing already processed claims.
     *
     * @return true if claim is APPROVED, REJECTED, or WITHDRAWN
     */
    public boolean isTerminalState() {
        return ClaimStatus.APPROVED.equals(status)
            || ClaimStatus.REJECTED.equals(status)
            || ClaimStatus.WITHDRAWN.equals(status);
    }

    /**
     * Checks if the claim is pending review (initial state).
     * @return true if status is PENDING
     */
    public boolean isPending() {
        return ClaimStatus.PENDING.equals(status);
    }
}
