package com.insurance.entity;

import com.insurance.enums.PolicyStatus;
import com.insurance.enums.PolicyType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║                          POLICY ENTITY                                  ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║                                                                          ║
 * ║  Represents an insurance policy contract between the insurance company  ║
 * ║  and a customer. The policy defines what is covered, for how much,      ║
 * ║  and for what period.                                                   ║
 * ║                                                                          ║
 * ║  RELATIONSHIPS:                                                          ║
 * ║  Customer (1) ─── (N) Policy  [Policy owns FK: customer_id]            ║
 * ║  Policy   (1) ─── (N) Claim   [Claim owns FK: policy_id]               ║
 * ║                                                                          ║
 * ║  INTERVIEW TIP: BigDecimal for Money                                    ║
 * ║  ─────────────────────────────────────────────────────────────────────  ║
 * ║  NEVER use double/float for financial values.                           ║
 * ║  double: 0.1 + 0.2 = 0.30000000000000004 (floating point imprecision)  ║
 * ║  BigDecimal: exact representation, arbitrary precision.                 ║
 * ║  @Column(precision=15, scale=2) → maps to NUMERIC(15,2) in PostgreSQL  ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */
@Entity
@Table(
    name = "policies",
    indexes = {
        @Index(name = "idx_policies_customer_id", columnList = "customer_id"),
        @Index(name = "idx_policies_status", columnList = "status"),
        @Index(name = "idx_policies_policy_number", columnList = "policy_number", unique = true)
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Policy {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Business-facing policy identifier. Generated by PolicyService.
     * Format: POL-YYYYMMDD-XXXXX (e.g., POL-20240115-00001)
     *
     * INTERVIEW TIP: Why have both `id` (surrogate key) and `policyNumber` (natural key)?
     * - Surrogate key (id): Internal, never changes, used for FK relationships
     * - Natural key (policyNumber): Business-facing, shown to customers, on documents
     * Separating them gives flexibility: business can rename policies without
     * changing internal database relationships.
     */
    @Column(name = "policy_number", nullable = false, unique = true, length = 30)
    private String policyNumber;

    @Column(name = "policy_name", nullable = false, length = 200)
    private String policyName;

    /**
     * @Enumerated(EnumType.STRING) → Stores "LIFE", "HEALTH", etc. as VARCHAR
     * Maps to our PolicyType enum.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "policy_type", nullable = false, length = 30)
    private PolicyType policyType;

    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * BigDecimal with precision=15, scale=2.
     * precision=15 → total 15 significant digits
     * scale=2 → 2 digits after the decimal point
     * Maps to: NUMERIC(15, 2) in PostgreSQL
     * Example: 5,000,000.00 is stored as 500000000 (integer representation internally)
     */
    @Column(name = "coverage_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal coverageAmount;

    /**
     * Premium amount: calculated by PremiumCalculationService.
     * Formula: basePremium × policyTypeRate × riskMultiplier
     */
    @Column(name = "premium_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal premiumAmount;

    /**
     * LocalDate: maps to DATE in PostgreSQL (no time component).
     * The policy is in force from startDate (inclusive) to endDate (inclusive).
     */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private PolicyStatus status = PolicyStatus.PENDING;

    @Column(name = "premium_frequency", length = 20)
    @Builder.Default
    private String premiumFrequency = "MONTHLY";

    /**
     * @ManyToOne: Many policies belong to one customer.
     * @JoinColumn: This table holds the FK column "customer_id".
     *   → Policy is the OWNING side of the Customer-Policy relationship.
     * fetch = LAZY: Customer not loaded when Policy is loaded.
     *   (prevents loading the entire customer graph just to display a policy)
     *
     * INTERVIEW TIP: Why @ManyToOne fetch defaults to EAGER?
     * JPA spec: @ManyToOne and @OneToOne default to EAGER.
     * @OneToMany defaults to LAZY.
     * Best practice: always override to LAZY for @ManyToOne to prevent
     * N+1 queries (each policy load would trigger a customer load).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    /**
     * @OneToMany: One Policy can have many Claims.
     * mappedBy = "policy" → Claim entity holds the FK.
     * fetch = LAZY → Claims not loaded unless explicitly accessed.
     */
    @OneToMany(mappedBy = "policy", cascade = CascadeType.ALL,
               fetch = FetchType.LAZY, orphanRemoval = true)
    @Builder.Default
    private List<Claim> claims = new ArrayList<>();

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // ─── HELPER METHODS ───────────────────────────────────────────────────

    /**
     * Checks if this policy is currently active (not expired or cancelled).
     * Used in ClaimService to enforce business rule: "cannot claim against inactive policy".
     *
     * @return true if status is ACTIVE and today is within the policy period
     */
    public boolean isActiveAndInForce() {
        return PolicyStatus.ACTIVE.equals(status)
            && !LocalDate.now().isBefore(startDate)
            && !LocalDate.now().isAfter(endDate);
    }

    /**
     * Checks if the policy has passed its end date.
     * Used by the @Scheduled policy expiry job.
     *
     * @return true if end date has passed
     */
    public boolean isPastEndDate() {
        return LocalDate.now().isAfter(endDate);
    }
}
